### ISSUE TITLE
TLS12 causes systems that are online to go into a corrective change loop

### ISSUE THREAD

**Issue by paesbiger** [EncoreTechnologies/puppet-powershellmodule#12]
For a subset of our systems we keep getting corrective changes. This is because of the try statement in get-psrepositories. When it fails the rest of the module assumes that the repo isn't installed and tries to install it again. 

Following the thread from the hbuckle version this seems to be related to the usage of TLS1.2 now being standard for the CDN's. 

Adding: [Net.ServicePointManager]::SecurityProtocol += [Net.SecurityProtocolType]::Tls12 on row  87 of /lib/puppet/provider/psrepository/powershellcore.rb seems to solve it for us.

**Comment by nmaludy** [comment]
@gsperry2011 can you look into this?
